"""add home_id to Booking

Revision ID: c0d42287d447
Revises: c92c6d565373
Create Date: 2024-01-24 10:50:02.763797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0d42287d447'
down_revision = 'c92c6d565373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_id', sa.Integer(), nullable=False))
        batch_op.alter_column('home_booked',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('check_in',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('check_out',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.create_foreign_key(None, 'home', ['home_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('check_out',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('check_in',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('home_booked',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('home_id')

    # ### end Alembic commands ###
