"""Updated migration

Revision ID: c92c6d565373
Revises: 38ee1d55e3e7
Create Date: 2024-01-24 07:22:20.170209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c92c6d565373'
down_revision = '38ee1d55e3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('check_out',
               existing_type=mysql.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('password', ['password'], unique=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('check_out',
               existing_type=sa.Date(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
